# Title: Sediment stress - pdam GOseq
# Author: Jill Ashey
# date: 2/1/2021

### Gene Ontology Analysis of Differentially Expressed Genes in Pdam
# Using updated GO terms (terms generated by Blast2GO, Interproscan, and Uniprot )

# Load packages 
library("DESeq2")
library("tidyverse")
library("dplyr")
library("pheatmap")
library("RColorBrewer")
library("genefilter")
library("ggplot2")
library("gplots")
library("limma")
library("spdep") 
library("adegenet") 
library("goseq")
library("forcats")
library("gridExtra")
library("gapminder")

# Obtain names of all expressed ofav genes (poverA = 0.85,5), and all differentially expressed planuala genes (p<0.05)
gcounts_filt_pdam <- read.csv("~/Desktop/PutnamLab/Repositories/SedimentStress/SedimentStress/Output/DESeq2/pdam/pdam_counts_filt.csv", header = TRUE) # read data in
dim(gcounts_filt_pdam) # 13881 rows x 13
#for ( col in 1:ncol(gcounts_filt_pdam)){
# colnames(gcounts_filt_pdam)[col] <-  gsub("X", "", colnames(gcounts_filt_pdam)[col]) # remove X in front of col names
#}
colnames(gcounts_filt_pdam)[1] <-"gene_id" # make colnames a true column called gene_id
head(gcounts_filt_pdam)
length(unique(gcounts_filt_pdam$gene_id)) # 13881 total unique gene ids

# Import file with DEGs for pdam
DEG_pdam <- read.csv("~/Desktop/pdam_unique.sig.list_20210326.csv", header = TRUE) # read in list of significant pdam genes
dim(DEG_pdam) # 549 x 13
#for ( col in 1:ncol(DEG_pdam)){
#   colnames(DEG_pdam)[col] <-  gsub("X", "", colnames(DEG_pdam)[col]) # remove X in front of col names
# }
colnames(DEG_pdam)[1] <-"gene_id" # make colnames a true column called gene_id
head(DEG_pdam)
length(unique(DEG_pdam$gene_id)) # 549 total unique gene ids 


#### Need to match up LOC term with XM ID in pdam length data 



# read in reference annotation gff file
ref <- read.csv("~/Desktop/GFFs/GCF_003704095.1_ASM370409v1_genomic.gff",header = FALSE, sep="\t", skip=6)
colnames(ref) <- c("scaffold", "Gene.Predict", "id", "gene.start","gene.stop", "pos1", "pos2","pos3", "attr") # name cols
ref <- subset(ref, id=="mRNA")
ref <- ref[!grepl("##", ref$scaffold),] # remove rows that have a # in scaffold col
#ref <- ref[grep("XM", ref$attr), ] # isolate XM protein name
ref$gene <- regmatches(ref$attr, gregexpr("(?<=gene=).*", ref$attr, perl = TRUE)) #removing everything in Symbol col up to LOC and creating new col called gene_id
ref$gene <- gsub(";.*", "", ref$gene) # remove everything after ;
ref$XM <- gsub(";.*", "", ref$attr)
ref$XM <- gsub("ID=", "", ref$XM)
ref$XM <- gsub(".*-", "", ref$XM)

# Read in length data (calculated directly from transcripts) and merge with filtered counts 
length_Pdam <- read.csv("Desktop/length.mRNA_Pdam.csv", header = FALSE)
colnames(length_Pdam) <- c("XM", "length")

# Merge XM names from ref annotation file with length file 
XM_merge <- merge(ref, length_Pdam, by = "XM")
XM_merge <- unique(XM_merge)
XM_merge <- select(XM_merge, c("XM", "gene", "length"))
colnames(XM_merge) <- c("XM", "gene_id", "length")

# Merge length data with filtered counts 
length_merge <- merge(XM_merge, gcounts_filt_pdam, by = "gene_id", all.x = T)
length_merge <- unique(length_merge)


#### Build GOSEQ vector 
#GOseq requires a vector of all genes, all differentially expressed genes, and gene lengths
# Make DEG/gene vector 
DEG <- filter(length_merge, gene_id%in%DEG_pdam$gene_id) #make vector of differentially expressed genes
dim(DEG) # 593 rows 
DEG_names <- as.vector(DEG$gene_id)
gene_vector=as.integer(length_merge$gene_id%in%DEG_names)
names(gene_vector)=length_merge$gene_id
# 17119

# Make ID vector 
IDvector <- length_merge$gene_id
# 17119

# Make length vector
lengthVector <- length_merge$length
# 17119

# Calculate Probability Weighting Function
DEG.pwf<-nullp(gene_vector, IDvector, bias.data=lengthVector) #weight vector by length of gene
# plot looks weird...does this mean that there is not much length bias in the dataset?



















### I dont think i actually need to use the merged file at all...all the info I need to merge with gcounts_filt is in ref (gene id and length)
#Import merged annotated gtf file. This was created with stringTie and merged all info about genes expressed in pdam for all samples
map <- read.csv("~/Desktop/GFFs/Pdam.merged.annotated.gtf", header=FALSE, sep="\t") # merged annotated pdam file created with stringTie
colnames(map) <- c("scaffold", "Gene.Predict", "id", "gene.start","gene.stop", "pos1", "pos2","pos3", "attr") # name columns
map <- map[!grepl("#", map$scaffold),] # remove rows that have a # in scaffold col
map <- map[grep("LOC", map$attr), ] # select all rows that have LOC in attr col
map$gene_id <- regmatches(map$attr, gregexpr("(?<=gene_name).*", map$attr, perl = TRUE)) #removing everything in Symbol col up to LOC and making new col called gene_id
map$gene_id <- gsub(";.*", "", map$gene_id) # remove everything after ;
map$gene_id <- gsub(" ", "", map$gene_id) # remove any blank spaces
map <- subset(map, id=="transcript") # select only transcripts
map <- select(map, c(gene_id)) # keep only gene id col
map_unique <- unique(map) # keep unique rows only
dim(map_unique) # 26139 x 4
length(unique(map_unique$gene_id)) # 22734 unique geneids
# # in this map file, there are 22734 unique gene ids. 

# Import reference annotation gff file. This is from NCBI
ref <- read.csv("~/Desktop/GFFs/GCF_003704095.1_ASM370409v1_genomic.gff",header = FALSE, sep="\t", skip=6) # ref file from NCBI
colnames(ref) <- c("scaffold", "Gene.Predict", "id", "gene.start","gene.stop", "pos1", "pos2","pos3", "attr") # name cols
ref <- ref[!grepl("##sequence", ref$scaffold),] # remove rows that have a # in scaffold col
#ref <- subset(ref, id == "gene") # select only genes -- skipping this for now because I am having some issues with using nullp and lengths of vectors 
#ref <- ref[grep("XP", ref$attr), ] # isolate XP protein name
#ref$prot <- gsub(";.*", "", ref$attr)
#ref$prot <- gsub("ID=", "", ref$prot)
#ref$prot <- gsub(".*-", "", ref$prot)
ref$gene_id <- regmatches(ref$attr, gregexpr("(?<=gene=).*", ref$attr, perl = TRUE)) #removing everything in Symbol col up to LOC and creating new col called gene_id
ref$gene_id <- gsub(";.*", "", ref$gene_id) # remove everything after ;
ref <- ref[!grepl("character", ref$gene_id),] # remove rows that have 'character' in gene_id col
ref <- select(ref, c(scaffold, gene.start, gene.stop, id, gene_id)) # select only certain cols
ref <- ref %>% mutate(ref, length = gene.stop - gene.start) # calculate gene length
dim(ref) # 484440 x 6
length(unique(ref$gene_id)) # 22799 
ref <- unique(ref) 
dim(ref) # 388598 x 6
ref <- subset(ref, id == "gene") # select only genes -- maybe i do need to do this step??
dim(ref) # 21837 x 6
length(unique(ref$gene_id)) # 21562 
# in this ref file, there are 21562 unique gene ids 
# Strange that the map file (created by me with stringTie) has more unique gene ids that the ref file (from NCBI). It could be because star/stringTie created 'novel' genes based on 
# exons splicing in different ways.
# I only need gene id and length...going to keep just those and throw out scaffold and gene start/stop
ref <- select(ref, c(length, gene_id)) # select only certain cols

# Build a df that merges gene IDs of expressed genes (poverA) from gcounts_filt_pdam and gene length from ref
# pdam_filt_ref <- merge(ref, gcounts_filt_pdam, by = "gene_id", all.x = TRUE)
# pdam_filt_ref <- na.omit(pdam_filt_ref)
# dim(pdam_filt_ref) # 13568 x 14
# I thought it supposed to be = to the number of expressed genes (13381), but some genes had no length (and so had NAs)
# Not going to keep them around because goseq needs gene length to do proper calculations
# Let's see if its okay that pdam_filt_ref = 13568 unique gene ids

# Build a dataframe that links the gene IDs of expressed genes (poverA = 0.85,5; gcounts_filt_pdam) and the gene IDs of those genes in the merged annotation file (from the gene map; map_unique)
pdam_filt.map_unique <- merge(gcounts_filt_pdam, map_unique, by = "gene_id", all.x = TRUE, all.y = TRUE) # merge gene counts and map by gene_id
pdam_filt.map_unique <- na.omit(pdam_filt.map_unique)
length(unique(pdam_filt.map_unique$gene_id))
dim(pdam_filt.map_unique)
# This seems to merely confirm that there are 13881 DEGs that were actually identified in stringTie

#Find gene positions in ref corresponding to expressed genes 
pdam_filt.map_unique.ref <- merge(pdam_filt.map_unique, ref, by = "gene_id", all.x= TRUE) # merge pdam_filt.map_unique and ref by gene_idpdam_filt.map_unique.ref <- select(pdam_filt.map_unique.ref, -c(scaffold.x, gene.start.x, gene.stop.x)) # remove specified cols
#pdam_filt.map_unique.ref <- na.omit(pdam_filt.map_unique.ref) 
#not going to omit NAs right now because some genes do not have a length (and thus have NAs)
#even though the genes that not have lengths will most likely not be used, still want to keep them around for now
dim(pdam_filt.map_unique.ref) # 13881 x 14


#### Build GOSEQ vector 
#GOseq requires a vector of all genes and all differentially expressed genes. 
#Make gene vector
DEG <- filter(pdam_filt.map_unique.ref, gene_id%in%DEG_pdam$gene_id) #make vector of differentially expressed genes
DEG <- DEG$gene_id
DEG <- unique(DEG)
DEG <- as.data.frame(DEG)
colnames(DEG) <- "gene_id"
dim(DEG) #should be same # of rows as DEG_pdam - it is! 549
DEG_names <- as.vector(DEG$gene_id)

# Make vector of all expressed genes (poverA = 0.85,5) with
# non-differentially expressed genes as 0 and differentially expressed genes as 1
gene_vector=as.integer(pdam_filt.map_unique.ref$gene_id%in%DEG_names)
names(gene_vector)=pdam_filt.map_unique.ref$gene_id
head(gene_vector)

#Make ID vector
ID_vector <- pdam_filt.map_unique.ref$gene_id
head(ID_vector)

#Make length vector
length_vector <- pdam_filt.map_unique.ref$length
head(length_vector)

#Calculate Probability Weighting Function
DEG.pwf<-nullp(gene_vector, ID_vector, bias.data=length_vector) #weight vector by length of gene
sum(is.na(DEG.pwf$pwf)) # 313 out of 13881 genes do not have lengths
# NAs in nullp: https://rdrr.io/bioc/goseq/man/nullp.html
# plot looks strange ???


### Prepare GO term dataframe 
# Import GO terms
annot_GO <- read.csv("~/Desktop/PutnamLab/Repositories/SedimentStress/SedimentStress/Output/GOSeq/pdam/pdam_GO_20210125.csv", header=TRUE)
annot_GO <- select(annot_GO, -X)
annot_GO$GO.ID <- gsub(",", ";", annot_GO$GO.ID)
#annot_GO$gene_id <- gsub("-.*", "", annot_GO$gene_id)

# Split GO terms so there is only 1 GO term per row
GO.terms <- separate_rows(annot_GO, GO.ID, sep = ";")
GO.terms <- unique(GO.terms)
colnames(GO.terms) <- c("gene_id", "GO.ID")
GO.terms <- GO.terms[!grepl("NA", GO.terms$GO.ID),]

# Merge GO terms with all expressed acerv genes 
GO.terms <- merge(GO.terms, pdam_filt.map_unique.ref, by.x="gene_id")
dim(GO.terms) # 20987 x 15

# Clean up GO.terms sd
GO.terms <- select(GO.terms, gene_id, GO.ID)
GO.terms$GO.ID <- replace_na(GO.terms$GO.ID, "unknown")
GO.terms$gene_id <- gsub(" ", "", GO.terms$gene_id)
head(GO.terms, 10)
tail(GO.terms, 10)


### Perform GOseq
# Find enriched GO terms, "selection-unbiased testing for category enrichment amongst differentially expressed (DE) genes for RNA-seq data"
GO.wall<-goseq(DEG.pwf, ID_vector, gene2cat=GO.terms, method="Wallenius", use_genes_without_cat=TRUE)
# Using manually entered categories.
# Calculating the p-values...
# 'select()' returned 1:1 mapping between keys and columns
write.csv(GO.wall, file = "~/Desktop/pdam_GO_ALL_20210207.csv")


#### Explore enriched GO terms
class(GO.wall)
dim(GO.wall) # 1880 x 7
head(GO.wall)
tail(GO.wall)
#Find overrepresented (expressed more?) enriched GO terms that are statistically significant at cutoff (p<0.05)
enriched.GO.05 <- GO.wall$category[GO.wall$over_represented_pvalue<0.05]
enriched.GO.05 <- data.frame(enriched.GO.05)
dim(enriched.GO.05) # 33
colnames(enriched.GO.05) <- c("category")
enriched.GO.05 <- merge(enriched.GO.05, GO.wall, by="category")
enriched.GO.05 <- enriched.GO.05[order(-enriched.GO.05$numDEInCat),]
enriched.GO.05$term <- as.factor(enriched.GO.05$term)
head(enriched.GO.05)
#Subset enriched GO terms by category and save as csv
MF <- subset(enriched.GO.05, ontology=="MF")
MF <- MF[order(-MF$numDEInCat),]
CC <- subset(enriched.GO.05, ontology=="CC") # no CC significantly enriched go terms
CC <- CC[order(-CC$numDEInCat),]
BP <- subset(enriched.GO.05, ontology=="BP")
BP <- BP[order(-BP$numDEInCat),]
write.csv(MF, file = "~/Desktop/pdam_MF_Sig_Enriched_GO.05_20210207.csv")
write.csv(CC, file = "~/Desktop/pdam_CC_Sig_Enriched_GO.05_20210207.csv")
write.csv(BP, file = "~/Desktop/pdam_BP_Sig_Enriched_GO.05_20210207.csv")
write.csv(enriched.GO.05, file = "~/Desktop/pdam_Sig_Enriched_GO.05_ALL_20210207.csv")

# Merge enriched GO terms with gene ids (from GO.terms df)
colnames(GO.terms) <- c("gene_id","category")
GO.terms_gene_ids <- merge(enriched.GO.05, GO.terms, by = "category", all.x = TRUE) # this combines gene ids with GO info from goseq analysis by GO term
GO.terms_gene_ids <- unique(GO.terms_gene_ids)
GO.terms_gene_ids.pdam_genes.map_unique.ref <- merge(GO.terms_gene_ids, pdam_filt.map_unique.ref, by = "gene_id") # this combines GO info with counts and length data by gene id 
#GO.terms_gene_ids.pdam_genes.map_unique.ref <- select(GO.terms_gene_ids.pdam_genes.map_unique.ref, c(gene_id, scaffold, start, stop, length, category, over_represented_pvalue, under_represented_pvalue, numDEInCat, numInCat, term, ontology ))
GO.terms_gene_ids.pdam_genes.map_unique.ref <- na.omit(GO.terms_gene_ids.pdam_genes.map_unique.ref)
write.csv(GO.terms_gene_ids.pdam_genes.map_unique.ref, file = "~/Desktop/pdam_GOterms_gene_ids_20210208.csv")

# Merge GO.terms_gene_ids.acerv_genes.map_unique.ref and treatment comparison list 
DEG_treatment <- read.csv("~/Desktop/pdam_DEGs.all_treatment_20210208.csv", header = TRUE)
#colnames(DEG_treatment)[1] <-"gene_id"
ByTreatment_GO.terms <- merge(DEG_treatment, GO.terms_gene_ids.pdam_genes.map_unique.ref, by = "gene_id", all.x = T) # this combines GO info, counts, and lengths with DEG treatment info by gene id 
ByTreatment_GO.terms <- na.omit(ByTreatment_GO.terms)
dim(ByTreatment_GO.terms) # 26 x 41
length(unique(ByTreatment_GO.terms$gene_id)) # 21 unique gene ids 
#ByTreatment_GO.terms <- filter(ByTreatment_GO.terms, over_represented_pvalue > 0)
############### THIS IS WHERE I NEED TO GET THE GENE IDS TO BLAST
# now I have a df with gene ids, treatment comparisons, GO terms, and term info
# in order for a gene id to make it onto this list, it has to:
#1) be differentially expressed 
#2) have length data from gff file 
#3) have GO term(s) assigned to it 
MF_ByTreatment <- subset(ByTreatment_GO.terms, ontology=="MF")
MF_ByTreatment <- MF_ByTreatment[order(-MF_ByTreatment$numDEInCat),]
CC_ByTreatment <- subset(ByTreatment_GO.terms, ontology=="CC")
CC_ByTreatment <- CC_ByTreatment[order(-CC_ByTreatment$numDEInCat),]
BP_ByTreatment <- subset(ByTreatment_GO.terms, ontology=="BP")
BP_ByTreatment <- BP_ByTreatment[order(-BP$numDEInCat),]
write.csv(MF_ByTreatment, file = "~/Desktop/pdam_MF_Sig_Enriched_ByTreatment_GO.05_20210208.csv")
write.csv(CC_ByTreatment, file = "~/Desktop/pdam_CC_Sig_Enriched_ByTreatment_GO.05_20210208.csv")
write.csv(BP_ByTreatment, file = "~/Desktop/pdam_BP_Sig_Enriched_ByTreatment_GO.05_20210208.csv")
write.csv(ByTreatment_GO.terms, file = "~/Desktop/pdam_ByTreatment_GO.terms_20210208.csv")

# Plot terms by number of differentially expressed functions
MFplot <- MF %>% mutate(term = fct_reorder(term, numDEInCat)) %>%
  ggplot( aes(x=term, y=numDEInCat) ) +
  geom_segment( aes(x=term ,xend=term, y=0, yend=numDEInCat), color="grey") +
  geom_point(size=3, color="#69b3a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="none"
  ) +
  xlab("") +
  ylab("") +
  ggtitle("Molecular Function") + #add a main title
  theme(plot.title = element_text(face = 'bold', 
                                  size = 12, 
                                  hjust = 0)) +
  theme_bw() + #Set background color 
  theme(panel.border = element_blank(), # Set border
        panel.grid.major = element_blank(), #Set major gridlines
        panel.grid.minor = element_blank(), #Set minor gridlines
        axis.line = element_line(colour = "black"), #Set axes color
        plot.background=element_blank())#Set the plot background
MFplot

CCplot <- CC %>% mutate(term = fct_reorder(term, numDEInCat)) %>%
  ggplot( aes(x=term, y=numDEInCat) ) +
  geom_segment( aes(x=term ,xend=term, y=0, yend=numDEInCat), color="grey") +
  geom_point(size=3, color="#69b3a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="none"
  ) +
  xlab("") +
  ylab("") +
  ggtitle("Cellular Component") + #add a main title
  theme(plot.title = element_text(face = 'bold', 
                                  size = 12, 
                                  hjust = 0)) +
  theme_bw() + #Set background color 
  theme(panel.border = element_blank(), # Set border
        panel.grid.major = element_blank(), #Set major gridlines
        panel.grid.minor = element_blank(), #Set minor gridlines
        axis.line = element_line(colour = "black"), #Set axes color
        plot.background=element_blank())#Set the plot background
CCplot

BPplot <- BP %>% mutate(term = fct_reorder(term, numDEInCat)) %>%
  ggplot( aes(x=term, y=numDEInCat) ) +
  geom_segment( aes(x=term ,xend=term, y=0, yend=numDEInCat), color="grey") +
  geom_point(size=3, color="#69b3a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="none") +
  xlab("") +
  ylab("") +
  ggtitle("Biological Process") + #add a main title
  theme(plot.title = element_text(face = 'bold', 
                                  size = 12, 
                                  hjust = 0)) +
  theme_bw() + #Set background color 
  theme(panel.border = element_blank(), # Set border
        panel.grid.major = element_blank(), #Set major gridlines
        panel.grid.minor = element_blank(), #Set minor gridlines
        axis.line = element_line(colour = "black"), #Set axes color
        plot.background=element_blank())#Set the plot background
BPplot

# Save MF, CC, and BP plot in grid layout
GOplot <- grid.arrange(MFplot, CCplot, BPplot, ncol=3, clip="off")
ggsave("~/Desktop/pdam_GOplot_05_20210208.pdf", GOplot, width = 21, height = 21, units = c("in"))


# Combining MF, CC, and BP into one plot and order by pvalue
GOplot2 <- enriched.GO.05 %>% drop_na(ontology) %>% mutate(term = fct_reorder(term, numDEInCat)) %>%
  mutate(term = fct_reorder(term, ontology)) %>%
  ggplot( aes(x=term, y=numDEInCat) ) +
  geom_segment( aes(x=term ,xend=term, y=0, yend=numDEInCat), color="grey") +
  geom_text(aes(label = over_represented_pvalue), hjust = -1, vjust = 0, size = 2) +
  geom_point(size=3, aes(colour = ontology)) +
  coord_flip() +
  ylim(0,55) +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="bottom"
  ) +
  xlab("") +
  ylab("") +
  theme_bw() + #Set background color 
  theme(panel.border = element_blank(), # Set border
        panel.grid.major = element_blank(), #Set major gridlines
        panel.grid.minor = element_blank(), #Set minor gridlines
        axis.line = element_line(colour = "black"), #Set axes color
        plot.background=element_blank()) #Set the plot background #set title attributes
GOplot2
ggsave("~/Desktop/pdam_GOplot2_05_20210208.pdf", GOplot2, width = 28, height = 28, units = c("in"))

# Combining into one plot and order by pvalue 
GOplot_pvalue <- enriched.GO.05 %>% drop_na(ontology) %>% mutate(term = fct_reorder(term, over_represented_pvalue)) %>%
  mutate(term = fct_reorder(term, ontology)) %>%
  ggplot( aes(x=term, y=over_represented_pvalue) ) +
  geom_segment( aes(x=term ,xend=term, y=0, yend=over_represented_pvalue), color="grey") +
  geom_text(aes(label = numDEInCat), hjust = -1, vjust = 0.5, size = 3) +
  geom_point(size=3, aes(colour = ontology)) +
  coord_flip() +
  ylim(0,0.05) +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="bottom"
  ) +
  xlab("") +
  ylab("p-value") +
  theme_bw() + #Set background color 
  theme(panel.border = element_blank(), # Set border
        panel.grid.major = element_blank(), #Set major gridlines
        panel.grid.minor = element_blank(), #Set minor gridlines
        axis.line = element_line(colour = "black"), #Set axes color
        plot.background=element_blank()) #Set the plot background #set title attributes
GOplot_pvalue
ggsave("~/Desktop/pdam_GOplot_pvalue_05_20210208.pdf", GOplot_pvalue, width = 28, height = 28, units = c("in"))


