# Title: Sediment stress - plob GOseq
# Author: Jill Ashey
# date: 1/2/2021

### Gene Ontology Analysis of Differentially Expressed Genes in Plob
# Using updated GO terms (terms generated by Blast2GO, Interproscan, and Uniprot )


# Load packages 
library("DESeq2")
library("tidyverse")
library("dplyr")
library("pheatmap")
library("RColorBrewer")
library("genefilter")
library("ggplot2")
library("gplots")
library("limma")
library("spdep") 
library("adegenet") 
library("goseq")
library("forcats")
library("gridExtra")
library("gapminder")

# Obtain names of all expressed ofav genes (poverA = 0.85,5), and all differentially expressed planuala genes (p<0.05)
gcounts_filt_plob <- read.csv("~/Desktop/PutnamLab/Repositories/SedimentStress/SedimentStress/Output/DESeq2/plob_counts_filt.csv", header = TRUE)
dim(gcounts_filt_plob) # 15369 rows x 13
for ( col in 1:ncol(gcounts_filt_plob)){
  colnames(gcounts_filt_plob)[col] <-  gsub("X", "", colnames(gcounts_filt_plob)[col])
}
colnames(gcounts_filt_plob)[1] <-"gene_id"

# Load DEGs
DEG_plob <- read.csv("~/Desktop/PutnamLab/Repositories/SedimentStress/SedimentStress/Output/DESeq2/plob_unique.sig.list.csv", header = TRUE)
dim(DEG_plob) # 153 x 13
for ( col in 1:ncol(DEG_plob)){
  colnames(DEG_plob)[col] <-  gsub("X", "", colnames(DEG_plob)[col])
}
colnames(DEG_plob)[1] <-"gene_id"












